"""
Export VGGish mel filterbank matrix to a C++ header.

Generates VGGishMelConstants.h containing:
  - VGGISH_MEL_MATRIX[257 * 64]  (row-major filterbank: weight per FFT bin per mel bin)
  - Plus shape constants

VGGish uses HTK-style triangular mel filters between 125-7500 Hz, 64 bins,
with 257 spectrogram bins (FFT_size=512, real FFT only uses N/2+1 bins).

Run from inside ai_backend:
    python export_vggish_mel.py
"""
import os
import numpy as np
from torchvggish.mel_features import spectrogram_to_mel_matrix
from torchvggish import vggish_params

BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER_PATH = os.path.normpath(os.path.join(
    BACKEND_DIR, "..", "MusicAI_Visualizer", "Source", "MusicAI_Visualizer", "VGGishMelConstants.h"
))

# Match VGGish's exact parameters
WINDOW_LENGTH = int(round(vggish_params.SAMPLE_RATE * vggish_params.STFT_WINDOW_LENGTH_SECONDS))  # 400
HOP_LENGTH = int(round(vggish_params.SAMPLE_RATE * vggish_params.STFT_HOP_LENGTH_SECONDS))         # 160
FFT_LENGTH = 2 ** int(np.ceil(np.log(WINDOW_LENGTH) / np.log(2.0)))                                # 512
NUM_SPECTROGRAM_BINS = FFT_LENGTH // 2 + 1                                                          # 257
NUM_MEL_BINS = vggish_params.NUM_MEL_BINS                                                           # 64

print(f"VGGish parameters:")
print(f"  Sample rate     : {vggish_params.SAMPLE_RATE}")
print(f"  Window length   : {WINDOW_LENGTH} samples")
print(f"  Hop length      : {HOP_LENGTH} samples")
print(f"  FFT length      : {FFT_LENGTH}")
print(f"  Spectrogram bins: {NUM_SPECTROGRAM_BINS}")
print(f"  Mel bins        : {NUM_MEL_BINS}")
print(f"  Mel range       : {vggish_params.MEL_MIN_HZ} - {vggish_params.MEL_MAX_HZ} Hz")
print(f"  Log offset      : {vggish_params.LOG_OFFSET}")

print("\nComputing mel filterbank matrix...")
mel_matrix = spectrogram_to_mel_matrix(
    num_mel_bins=NUM_MEL_BINS,
    num_spectrogram_bins=NUM_SPECTROGRAM_BINS,
    audio_sample_rate=vggish_params.SAMPLE_RATE,
    lower_edge_hertz=vggish_params.MEL_MIN_HZ,
    upper_edge_hertz=vggish_params.MEL_MAX_HZ,
)
print(f"  matrix shape: {mel_matrix.shape}  (spectrogram_bins x mel_bins)")
print(f"  matrix range: [{mel_matrix.min():.4f}, {mel_matrix.max():.4f}]")
print(f"  non-zero    : {np.count_nonzero(mel_matrix)} / {mel_matrix.size}")

print(f"\nWriting {HEADER_PATH} ...")
os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
with open(HEADER_PATH, 'w', encoding='utf-8') as f:
    f.write("#pragma once\n\n")
    f.write("// =====================================================\n")
    f.write("// AUTO-GENERATED VGGish MEL FILTERBANK CONSTANTS\n")
    f.write("// Generated by ai_backend/export_vggish_mel.py\n")
    f.write("// Triangular mel filterbank, HTK-style scaling.\n")
    f.write("// =====================================================\n\n")

    f.write(f"#define VGGISH_MEL_WINDOW_LEN     {WINDOW_LENGTH}\n")
    f.write(f"#define VGGISH_MEL_HOP_LEN        {HOP_LENGTH}\n")
    f.write(f"#define VGGISH_MEL_FFT_SIZE       {FFT_LENGTH}\n")
    f.write(f"#define VGGISH_MEL_SPEC_BINS      {NUM_SPECTROGRAM_BINS}\n")
    f.write(f"#define VGGISH_MEL_NUM_BINS       {NUM_MEL_BINS}\n")
    f.write(f"#define VGGISH_MEL_NUM_FRAMES     96\n")
    f.write(f"#define VGGISH_MEL_LOG_OFFSET     {vggish_params.LOG_OFFSET}f\n\n")

    f.write("// Filterbank: VGGISH_MEL_MATRIX[s * VGGISH_MEL_NUM_BINS + m]\n")
    f.write("//   = weight applied to spectrogram bin s when computing mel bin m.\n")
    f.write(f"const float VGGISH_MEL_MATRIX[VGGISH_MEL_SPEC_BINS * VGGISH_MEL_NUM_BINS] = {{\n")
    for s in range(NUM_SPECTROGRAM_BINS):
        row = ", ".join(f"{v:.10f}f" for v in mel_matrix[s])
        f.write(f"    {row},\n")
    f.write("};\n")

print(f"\nDone. Wrote {NUM_SPECTROGRAM_BINS * NUM_MEL_BINS} float weights.")
print("Next: rebuild Unreal project to pick up the new header.")
