"""
Export VGGish PCA postprocessing constants to a C++ header.

Generates VGGishPCAConstants.h containing:
  - VGGISH_PCA_EIGEN[128 * 128]  (row-major eigen matrix)
  - VGGISH_PCA_MEANS[128]        (per-dim means subtracted before PCA)
  - VGGISH_QUANTIZE_MIN/MAX      (clip range)

Verifies output against Python's Postprocessor by running a dummy vector
through both paths and comparing.

Run from inside ai_backend:
    python export_vggish_pca.py
"""
import os
import torch
import numpy as np
from torchvggish.vggish import Postprocessor
from torchvggish import vggish_params

BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER_PATH = os.path.normpath(os.path.join(
    BACKEND_DIR, "..", "MusicAI_Visualizer", "Source", "MusicAI_Visualizer", "VGGishPCAConstants.h"
))

URLS = {
    'pca': 'https://github.com/harritaylor/torchvggish/releases/download/v0.1/vggish_pca_params-970ea276.pth'
}

print("Loading VGGish PCA params...")
state_dict = torch.hub.load_state_dict_from_url(URLS['pca'])
state_dict[vggish_params.PCA_EIGEN_VECTORS_NAME] = torch.as_tensor(
    state_dict[vggish_params.PCA_EIGEN_VECTORS_NAME], dtype=torch.float
)
state_dict[vggish_params.PCA_MEANS_NAME] = torch.as_tensor(
    state_dict[vggish_params.PCA_MEANS_NAME].reshape(-1, 1), dtype=torch.float
)

pproc = Postprocessor()
pproc.load_state_dict(state_dict)
pproc.eval()

eigen = pproc.pca_eigen_vectors.detach().cpu().numpy()  # [128, 128]
means = pproc.pca_means.detach().cpu().numpy().flatten()  # [128]

print(f"  eigen shape: {eigen.shape}")
print(f"  means shape: {means.shape}")
print(f"  quantize range: [{vggish_params.QUANTIZE_MIN_VAL}, {vggish_params.QUANTIZE_MAX_VAL}]")

# Verification: run a dummy embedding through both paths
print("\nVerifying numerical equivalence...")
dummy = torch.randn(1, 128)
expected = pproc(dummy).numpy().flatten()

# Manual reproduction (matches the C++ we'll write)
emb = dummy.numpy().flatten()
centered = emb - means
pca_applied = eigen @ centered  # [128, 128] @ [128] -> [128]
clipped = np.clip(pca_applied, vggish_params.QUANTIZE_MIN_VAL, vggish_params.QUANTIZE_MAX_VAL)
scale = 255.0 / (vggish_params.QUANTIZE_MAX_VAL - vggish_params.QUANTIZE_MIN_VAL)
manual = np.round((clipped - vggish_params.QUANTIZE_MIN_VAL) * scale)

max_diff = np.max(np.abs(expected - manual))
print(f"  Max difference between Python Postprocessor and manual matmul: {max_diff:.6f}")
assert max_diff < 1e-3, f"Mismatch! diff = {max_diff}"
print("  Verification PASSED. C++ implementation will produce identical results.")

# Write C++ header
print(f"\nWriting {HEADER_PATH} ...")
os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
with open(HEADER_PATH, 'w', encoding='utf-8') as f:
    f.write("#pragma once\n\n")
    f.write("// =====================================================\n")
    f.write("// AUTO-GENERATED VGGish PCA POSTPROCESSING CONSTANTS\n")
    f.write("// Generated by ai_backend/export_vggish_pca.py\n")
    f.write("// Do not edit by hand. Re-run the script to refresh.\n")
    f.write("// =====================================================\n\n")

    f.write("// PCA eigen vectors, row-major: VGGISH_PCA_EIGEN[i * 128 + j] = eigen[i, j]\n")
    f.write("const float VGGISH_PCA_EIGEN[128 * 128] = {\n")
    for i in range(128):
        row = ", ".join(f"{v:.10f}f" for v in eigen[i])
        f.write(f"    {row},\n")
    f.write("};\n\n")

    f.write("// Per-dimension means subtracted before PCA matmul\n")
    f.write("const float VGGISH_PCA_MEANS[128] = {\n")
    f.write("    " + ", ".join(f"{v:.10f}f" for v in means) + "\n")
    f.write("};\n\n")

    f.write(f"// Quantization range used for clip-and-quantize step\n")
    f.write(f"const float VGGISH_QUANTIZE_MIN = {vggish_params.QUANTIZE_MIN_VAL}f;\n")
    f.write(f"const float VGGISH_QUANTIZE_MAX = {vggish_params.QUANTIZE_MAX_VAL}f;\n")

print(f"\nDone. Constants written to {HEADER_PATH}")
print("Next: rebuild Unreal project to pick up the new header.")
